### ISSUE TITLE
Not working with /p:PublishSingleFile=true apps

### ISSUE THREAD

**Issue by IlyaSemenov** [Tyrrrz/Onova#28] opened 2020-01-21 10:03 UTC
If a project is built as a single file:

```bash
dotnet publish -c Release -r win-x86 /p:PublishSingleFile=true
zip -j $zip_file ./bin/Release/netcoreapp3.1/win-x86/publish/myapp.exe
```

then the app is not updated with this code:

```cs
using (var manager = new UpdateManager(
	new WebPackageResolver(Config.update_manifest_url),
	new ZipPackageExtractor()))
{
	var result = await manager.CheckForUpdatesAsync();
	if (result.CanUpdate)
	{
		// Prepare an update by downloading and extracting the package
		// (supports progress reporting and cancellation)
		await manager.PrepareUpdateAsync(result.LastVersion);

		// Launch an executable that will apply the update
		// (can be instructed to restart the application afterwards)
		manager.LaunchUpdater(result.LastVersion);

		// Terminate the running application so that the updater can overwrite files
		Environment.Exit(0);
	}
}
```

It correctly detects the new version, downloads it, runs LaunchUpdater, but the actual file is not replaced with the new version. It works fine without `/p:PublishSingleFile=true`.

**Comment by IlyaSemenov** [comment] 2020-01-21 10:35
Right, thank you for pointing to that issue. Anyhow I think this case deserves to be either documented or handled automatically.

**Comment by Tyrrrz** [comment] 2020-01-21 10:41
You are right. I will try to improve this area when I get around to it. I'll leave this issue open to track it.

**Comment by IlyaSemenov** [comment] 2020-01-21 11:11
Just some experiments:

```cs
using (var manager = new UpdateManager(
	AssemblyMetadata.FromAssembly(Assembly.GetEntryAssembly(), System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName),
	new WebPackageResolver(Config.update_manifest_url),
	new ZipPackageExtractor()))
```

this presumably should do it, but `app.updater.exe` is then stuck forever. (My wild guess is that it waits for the wrong assembly to exit.)

**Comment by Tyrrrz** [comment] 2020-01-21 11:19
Can you try the approach suggested in this comment for getting the file path?
https://github.com/Tyrrrz/Onova/issues/26#issuecomment-565358404

**Comment by IlyaSemenov** [comment] 2020-01-21 11:38
Yes, I tried it, too. The two methods, from #26:

```cs
Path.Join(Directory.GetCurrentDirectory(), Assembly.GetExecutingAssembly().GetName().Name + ".exe")
```

and the one I was using:

```cs
System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName
```
normally yield the same result, but the first method is clearly less reliable. It depends on the current directory which is not necessarily the directory where the executable file resides (e.g. if you start the app as `bin\app.exe` the first method will report incorrect path).

**Comment by Tyrrrz** [comment] 2020-01-21 11:48
Could be some useful information in this thread: https://github.com/dotnet/coreclr/issues/25623

**Comment by IlyaSemenov** [comment] 2020-01-21 11:58
Both methods above resolve to **correct path** (to the actual self-containing exe). The `GetCurrentProcess` method is just more reliable in the long run.

The log file was there but it was empty. (I'll check this once more it a bit.)

**Comment by Tyrrrz** [comment] 2020-01-21 12:04
Ok I see. So the main issue is that the updater hangs.
If the log is empty, that would probably mean it didn't even reach [the first log entry](https://github.com/Tyrrrz/Onova/blob/0a3bd9f5c2252e1b265234b28ea25f080b7cd3c2/Onova.Updater/Program.cs#L89). Even if the process is exited forcefully, it should still flush the data to file.

**Comment by levitatejay** [comment] 2020-03-14 02:03
I'm getting the updater hanging too as well as the empty log file...

I guess it is occurring on this line in the Updater: 
`while (!FileEx.CheckWriteAccess(updateeFilePath))`

I'm not sure how to debug it though... Is there a way I can work around this? I really want to use single file deployment with this library

**Comment by Tyrrrz** [comment] 2020-03-14 12:26
@levitatejay when the updater hangs, can you check whether the .exe file it's trying to update is still running? If it's not, can you check if you can delete it?

**Comment by levitatejay** [comment] 2020-03-15 03:41
@Tyrrrz when I try to delete the file I get: _"The action can't be completed because the file is open in Onova.Updater"_

**Comment by Tyrrrz** [comment] 2020-03-15 13:59
I just tried it out with

```csharp
AssemblyMetadata.FromAssembly(
                    Assembly.GetEntryAssembly(),
                    System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName)
```

and it worked.

Does anything happen differently if you pass `false` to `_updaterManager.LaunchUpdater`?

**Comment by Tyrrrz** [comment] 2020-04-04 15:51
Still can't reproduce this on my end :(
Could any of you provide a minimal repro project that exhibits the problem?

**Comment by bezzad** [comment] 2020-04-19 20:19
I have WPF.Net Core 3.1 project which has a problem in auto-update with Onova when the project published as a single file!
I check the execute path and find that the application created and unpacked itself in below path and when the update occurred the update files has also copied in below path:

`C:\Users\USERNAME\AppData\Local\Temp\.net\APPNAME\xxxxxxxxx`

So, another time when the user executes the application then old app runs.
I thought maybe this could help you fix it too.

**Comment by Tyrrrz** [comment] 2020-04-19 20:21
Did you override the assembly path as mentioned in the previous comments?

**Comment by bezzad** [comment] 2020-04-21 08:57
No, my update manager codes:

```csharp
Manager = new Onova.UpdateManager(
                new WebPackageResolver(AppSetting.BaseUrls.PackagesManifest),
                new ZipPackageExtractor());
```

**Comment by Tyrrrz** [comment] 2020-04-21 09:08
Try

```csharp
Manager = new Onova.UpdateManager(
	AssemblyMetadata.FromAssembly(
		Assembly.GetEntryAssembly(), 
		System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName),
	new WebPackageResolver(AppSetting.BaseUrls.PackagesManifest),
	new ZipPackageExtractor());
```

**Comment by bezzad** [comment] 2020-04-21 09:20
I tested that but can't update my app!

**Comment by Tyrrrz** [comment] 2020-04-21 09:47
What do you mean?

**Comment by bezzad** [comment] 2020-04-21 10:27
I tested the below code:
```
Manager = new Onova.UpdateManager(
	AssemblyMetadata.FromAssembly(
		Assembly.GetEntryAssembly(), 
		System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName),
	new WebPackageResolver(AppSetting.BaseUrls.PackagesManifest),
	new ZipPackageExtractor());
```

But I don't know why updater can't change anything!

**Comment by Tyrrrz** [comment] 2020-04-21 10:44
Can you make a minimal repro on GitHub that I can take a look at?

**Comment by bezzad** [comment] 2020-04-22 08:16
Sorry, I tested it on my main app that didn't work. Now I have made a small version of it so that I can send it to you instead of the original project, which I saw works perfectly. Maybe the problem is with my original app. Let me check more and if it doesn't work, I'll send you a copy.
Sorry about the time you left.

**Comment by levitatejay** [comment] 2020-04-25 07:41
> Still can't reproduce this on my end :(
> Could any of you provide a minimal repro project that exhibits the problem?

https://github.com/levitatejay/self-contained-update-stuck

Steps to reproduce:

1. Create a 1.0.0.0 self contained exe
2. Create a 2.0.0.0 self contained exe, zip it and place it as "c:/UpdateTest/Packages/SelfContainedUpdate-v2.0.0.0.zip"
3. Run v1 and select "Yes"

The SelfContainedUpdate.exe closes itself and if you try to delete it says its in use by Onova
The Onova process never closes

I think it is getting stuck here: https://github.com/Tyrrrz/Onova/blob/master/Onova.Updater/Updater.cs#L39

I need to see why the Updater doesn't have Write Access even though the exe not running anymore

**Comment by Tyrrrz** [comment] 2020-04-27 13:30
I follow the steps to reproduce and got this:

![image](https://user-images.githubusercontent.com/1935960/80377803-68a6d700-88a4-11ea-9a6c-d339c06eedd8.png)

Didn't change the code in any way. The update process took about 3-4 seconds, because the package is so large.

**Comment by Tyrrrz** [comment] 2020-04-27 13:35
Out of curiosity, do you have an antivirus running?

**Comment by levitatejay** [comment] 2020-04-30 06:25
Just Windows 10 with Windows Defender, on an Admin account too. 

Mine is definitely getting stuck, I've tried doing it from different directories too... Is there a way I can see more info on why it doesn't have write access ?

**Comment by Tyrrrz** [comment] 2020-04-30 07:08
I believe if you start CMD as admin, you can run `openfiles /query /fo table` to see the list of open file handles and the owner processes. Alternatively, I think you can use Process Explorer.

**Comment by levitatejay** [comment] 2020-05-01 23:17
I select "Yes" to update it and after a long of time I see Onova.Updater is still running and the exe hasn't updated.

From openfiles:

![image](https://user-images.githubusercontent.com/13340760/80847905-6e663900-8c65-11ea-8883-3ea4c2d27fb5.png)

When trying to delete `SelfContainedUpdate.exe`:

![image](https://user-images.githubusercontent.com/13340760/80847936-9190e880-8c65-11ea-8b40-0f447225f1e2.png)

Inside `C:\Users\...\AppData\Local\Onova\SelfContainedUpdate`:

![image](https://user-images.githubusercontent.com/13340760/80848006-d157d000-8c65-11ea-9762-da52db75180b.png)

Empty log.txt:

![image](https://user-images.githubusercontent.com/13340760/80848064-09f7a980-8c66-11ea-8d79-985881a20c57.png)

Do you have some other ideas I could try?

**Comment by Tyrrrz** [comment] 2020-05-02 12:17
Weird. It seems that `openfiles` claims that `SelfContained.exe` is in use by `SelfContained.exe` but Windows says it's open by `Onova.Updater`.

**Comment by Tyrrrz** [comment] 2020-05-02 12:20
Could you try the latest Onova binaries from master branch? I changed the logging to aggressively flush on each write, hopefully it will help reveal which stage it fails on.

**Comment by levitatejay** [comment] 2020-05-09 05:12
So the log now ends with:
`09-May-2020 17:04:09.200> Waiting for all running updatee instances to exit...`

However I've noticed something interesting. If I:

1. Delete the publish folder, publish it again
2. Run exe and select "Yes" to on the first run

**It works!** But if I:

1. Delete the publish folder, publish it again
2. Run exe and select "No" on the first run
3. Close program
4. Run exe and select "Yes" on the second run

It doesn't work... I also tried waiting ~10 minutes after closing the software, running it again and choosing yes - still no luck

**Comment by levitatejay** [comment] 2020-05-09 05:30
I updated access check in Updater.cs:
```
var canWrite = false;
while (canWrite == false)
{
    try
    {
        File.Open(updateeDirPath, FileMode.Open, FileAccess.Write).Dispose();
        canWrite = true;
    }
    catch (UnauthorizedAccessException ex)
    {
        WriteLog($"UnauthorizedAccessException: {ex.Message}");
    }
    catch (IOException ex)
    {
        WriteLog($"IOException: {ex.Message}");
    }
    Thread.Sleep(1000);
}
```

So if I run program, close, re-open and choose to update, log.txt:
```
09-May-2020 17:25:15.532> Waiting for all running updatee instances to exit...
09-May-2020 17:25:15.537> UnauthorizedAccessException: Access to the path 'C:\Projects\self-contained-update-stuck\SelfContainedUpdate\bin\Release\netcoreapp3.1\publish' is denied.
09-May-2020 17:25:16.538> UnauthorizedAccessException: Access to the path 'C:\Projects\self-contained-update-stuck\SelfContainedUpdate\bin\Release\netcoreapp3.1\publish' is denied.
09-May-2020 17:25:17.539> UnauthorizedAccessException: Access to the path 'C:\Projects\self-contained-update-stuck\SelfContainedUpdate\bin\Release\netcoreapp3.1\publish' is denied.
```

**Comment by Tyrrrz** [comment] 2020-05-09 10:18
Looks like this is a list of reasons for unauthorized access when calling `File.Open`:

![image](https://user-images.githubusercontent.com/1935960/81471066-2e6bfc80-91f7-11ea-8b42-7127379d0aaa.png)

It looks like the `path` is actually a directory, according to your logs. The `updateeFilePath` argument is passed by Onova and comes from here:

https://github.com/Tyrrrz/Onova/blob/898201ef6a450b5b50e1bce854625c45843dee58/Onova/Models/AssemblyMetadata.cs#L43-L50

Could it be that `assemblyFilePath` is somehow set to a directory instead of a file?

I guess that would mean that `System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName` evaluates to a directory somehow.

**Comment by Tyrrrz** [comment] 2020-05-09 10:20
There's this remark but I don't think that this file path is long enough (and that wouldn't explain why it works the first time either):

![image](https://user-images.githubusercontent.com/1935960/81471160-e00b2d80-91f7-11ea-9bff-94627863d3f4.png)

**Comment by Tyrrrz** [comment] 2020-05-09 10:21
Wait, nevermind, in your code you're actually doing `File.Open(updateeDirPath` which will always fail because `File.Open` can't be used on a directory.

**Comment by Tyrrrz** [comment] 2020-05-09 10:44
I was able to reproduce it by clicking "No" first.

**Comment by Tyrrrz** [comment] 2020-05-09 11:23
Ok it appears that the file becomes locked as soon as `Onova.Updater` even starts (before checking for write access). I think what happens is that the original parent process locks the file (probably happens when you run a self-contained exe and it unpacks files) and then `Onova.Updater` somehow inherits it as a child process?

I'm guessing the problem is caused by this issue: https://github.com/dotnet/runtime/issues/19569

**Comment by Tyrrrz** [comment] 2020-05-09 11:36
Looks like the bug is still under ongoing discussion since 2014 here: https://github.com/dotnet/runtime/issues/13943

It appears that `Process.Start` causes the child process to inherit all handles without actually being able to access it. So what happens is that self-contained app starts, unpacks itself (while locking the original self-contained exe), then at some point starts `Onova.Updater` which inherits the file handle but can't do anything with it.

It looks like Onova can't work with self-contained deployments until either MS provides a way to disable handle inheritance when starting processes or change how self-contained apps start so that they don't maintain a handle on the original executable file.

**Comment by Tyrrrz** [comment] 2020-05-09 15:18
Update: the fix to the self-contained problem will come in the next .NET update:

https://github.com/dotnet/runtime/issues/13943#issuecomment-626191085

**Comment by levitatejay** [comment] 2020-05-11 09:23
> Update: the fix to the self-contained problem will come in the next .NET update:
> 
> [dotnet/runtime#13943 (comment)](https://github.com/dotnet/runtime/issues/13943#issuecomment-626191085)

Oh great, thank you. Nice sleuthing!

**Comment by Tyrrrz** [comment] 2020-05-13 07:17
Looks like .NET Core SDK 3.1.4 is out. Can you test it and see if it works?

https://dotnet.microsoft.com/download/dotnet-core

**Comment by levitatejay** [comment] 2020-05-14 05:35
I've installed 3.1.4, Visual Studio 2019 16.5, removed all binaries and re-published but I'm getting the same experience

![image](https://user-images.githubusercontent.com/13340760/81896529-e5f27b80-9608-11ea-8d56-401d449e4679.png) 
![image](https://user-images.githubusercontent.com/13340760/81896580-01f61d00-9609-11ea-93bb-572b5ef06599.png)

**Comment by Tyrrrz** [comment] 2020-05-14 08:12
You are publishing with `-r win-x64` right?

**Comment by levitatejay** [comment] 2020-05-14 08:26
Yes
```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\netcoreapp3.1\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishTrimmed>True</PublishTrimmed>
  </PropertyGroup>
</Project>
```

**Comment by Tyrrrz** [comment] 2020-05-14 12:41
Hmm. So either their fix didn't do anything or it doesn't actually apply somehow. It's still the same issue with `Onova.Updater` claiming the lock on the .exe file?

**Comment by elestedt** [comment] 2020-09-27 13:28
@Tyrrrz I ran into this problem on my project and
        manager = new UpdateManager(
            AssemblyMetadata.FromAssembly(
		          Assembly.GetEntryAssembly(), 
		          System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName),
            new GithubPackageResolver("ipocsmr", "ipocs.dpt", "*" + os + "*"),
            new ZipPackageExtractor());
solved it for me.
I backported the fix to an older version (by removing a couple of tags locally) and the update replaced the file - which it did not do before.
Project can be found at https://github.com/ipocsmr/ipocs.dpt
The fix will be included in version 4.0.2 onwards to see if it works when it hits the wild.

**Comment by elestedt** [comment] 2020-10-11 18:34
@Tyrrrz I have now released two patches since 4.0.2 of that project - and both update properly with this workaround.

**Comment by Tyrrrz** [comment] 2020-10-12 10:44
Nice @elestedt

**Comment by svengeance** [comment] 2021-05-12 16:26
FWIW I can confirm this also works in a single-file .NET 5 app.

@Tyrrrz Is there any resolution that could make its way upstream here? I haven't seen a matrix of all of the ways we can detect assemblies and file paths, but is the `GetEntryAssembly` and `CurrentProcess.MainModule.FileName` a decent, publish-agnostic way to go about things?

Short of being **completely** agnostic, what about a flag (default-false) on the updater to ask the user if the project is single file?

**Comment by Tyrrrz** [comment] 2021-05-12 18:24
@svengeance `CurrentProcess.MainModule.FileName` is not publish-agnostic unfortunately.

- If the app is published as framework-dependent distribution and user runs the `exe` file, then they get the path to the `exe` file (good)
- If the app is published as framework-dependent distribution and user runs `dotnet app.dll`, then they get the path to the `dotnet` CLI instead (bad)
- If the app is published as self-contained distribution then the user will get the path to the `exe` file (good)
- If the app is published as self-contained single-file distribution then the user will get the path to the `exe` file (good)

Additionally, the current approach uses `assembly.Location` which always points to the `dll` file and never to the `exe`. Theoretically, it shouldn't be a problem since both files are typically in use at the same time, but still may result in some unforeseen consequences.

Also, the majority of the discussion in this thread was related to another related issue, where Onova would deadlock because it couldn't overwrite the files. I thought it would work with newer runtime after https://github.com/dotnet/runtime/issues/13943#issuecomment-626191085 was fixed, but apparently not.

**Comment by Tyrrrz** [comment] 2021-07-05 12:28
Random shower thought in regard to my comment above:

`Process.GetCurrentProcess().MainModule.FileName` may not work for us, but the main `dll` module should always be loaded in the process by this point too. I wonder if there's a way to order process module by when they were loaded and take the first `dll` module?

**Closed** 2023-01-14 17:51 UTC
Labels: bug, help wanted
